# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
